# Generated by Django 5.1.7 on 2025-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='social_links',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
