# Generated by Django 5.1.7 on 2025-03-20 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm_api.firm')),
            ],
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='firm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='llm_api.firm'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MainDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='llm_api.firm')),
            ],
        ),
    ]
