# Generated by Django 5.1.7 on 2025-04-02 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_api', '0007_remove_firm_latitude_remove_firm_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='firms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
