# Generated by Django 5.1.7 on 2025-04-22 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_api', '0009_alter_firm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='llm_api.document')),
                ('original_prompt', models.TextField()),
                ('topics', models.JSONField(default=dict)),
                ('urls', models.JSONField(blank=True, null=True)),
                ('full_report', models.TextField(blank=True, null=True)),
                ('cutdown_report', models.TextField(blank=True, null=True)),
                ('summary_report', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('llm_api.document',),
        ),
    ]
